Add "Ad-Hoc Mesh Networks with Satellites" project idea
freifunk/projects.freifunk.net-contents pull request #69
Opened 2022-02-12 17:13 UTC by mwarning

The task for the student would be to create a test tsetup to test mesh routing protocols (batman-adv, babel, ..) with satellites.

2022-02-12 17:59 UTC, andibraeu requested changes

2022-02-12 17:59 UTC, andibraeu commented on collections/_projects/freifunk-on-satellites.md
> +  - GSoC
please add `GSoC2022`, too

2022-02-12 17:59 UTC, andibraeu commented on collections/_projects/freifunk-on-satellites.md
> +---
we need the metadata `size` here.. please set
`size: half-time` or `size: full-time`

2022-02-12 17:59 UTC, andibraeu requested changes
please remove the testbed project file, if it is not needed anymore

2022-02-12 18:35 UTC, mwarning commented
@andibraeu I have added a MR to remove the testbed project: https://github.com/freifunk/projects.freifunk.net-contents/pull/71

2022-02-12 18:45 UTC, merged

2022-02-19 16:10 UTC, AmeyaKaloge commented
hey there, 
I am Amey. I have read about this project and I really want to contribute to this particular project also I want to participate this years GSoC. Kindly help me to start my contribution.

2022-02-19 21:29 UTC, mwarning commented
hi @AmeyaKaloge, nice to see you reaching out already.
If Freifunk will be selected (we will know on March 7) as participation GSoc organisation, then people can officially apply for projects starting April 4 (see https://developers.google.com/open-source/gsoc/timeline).

Feell free to email me and we can talk about what you are interested in and what you would like to achieve.